-- MYCO Notices module tables

CREATE TABLE IF NOT EXISTS myco_notices (
    id CHAR(36) PRIMARY KEY,
    notice_type ENUM('host_read_ads', 'sponsorship_vetting') NOT NULL,
    show_id CHAR(36) NOT NULL,
    brand_name VARCHAR(255) NOT NULL,
    ad_copy_link VARCHAR(2048) NULL,
    brand_overview VARCHAR(400) NULL,
    ad_type ENUM('endorsement', 'personal_experience') NULL,
    due_date DATE NOT NULL,
    notes VARCHAR(400) NULL,
    contact_name VARCHAR(255) NOT NULL,
    contact_email VARCHAR(255) NULL,
    contact_phone VARCHAR(64) NULL,
    contact_source ENUM('auto_primary', 'manual') NOT NULL DEFAULT 'auto_primary',
    channel_email BOOLEAN NOT NULL DEFAULT FALSE,
    channel_text BOOLEAN NOT NULL DEFAULT FALSE,
    channel_myco BOOLEAN NOT NULL DEFAULT FALSE,
    frequency_hours INT NOT NULL DEFAULT 24,
    reminder_window_days INT NOT NULL DEFAULT 7,
    reminder_started_at DATETIME NOT NULL,
    status ENUM('active', 'complete', 'cancelled', 'expired') NOT NULL DEFAULT 'active',
    last_sent_at DATETIME NULL,
    next_send_at DATETIME NOT NULL,
    send_count INT NOT NULL DEFAULT 0,
    myco_recipient_user_id CHAR(36) NULL,
    created_by CHAR(36) NOT NULL,
    completed_by CHAR(36) NULL,
    completed_at DATETIME NULL,
    cancelled_by CHAR(36) NULL,
    cancelled_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_myco_notices_status (status),
    INDEX idx_myco_notices_show_id (show_id),
    INDEX idx_myco_notices_next_send (status, next_send_at),
    INDEX idx_myco_notices_due_date (due_date),
    INDEX idx_myco_notices_created_at (created_at),
    INDEX idx_myco_notices_status_created_at (status, created_at),
    INDEX idx_myco_notices_notice_type (notice_type),
    INDEX idx_myco_notices_created_by (created_by),
    CONSTRAINT fk_myco_notices_show FOREIGN KEY (show_id) REFERENCES shows(id) ON DELETE CASCADE,
    CONSTRAINT fk_myco_notices_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_myco_notices_myco_user FOREIGN KEY (myco_recipient_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS myco_notice_deliveries (
    id CHAR(36) PRIMARY KEY,
    notice_id CHAR(36) NOT NULL,
    channel ENUM('email', 'text', 'myco') NOT NULL,
    status ENUM('sent', 'failed', 'skipped') NOT NULL,
    recipient VARCHAR(255) NULL,
    error_message TEXT NULL,
    external_id VARCHAR(255) NULL,
    is_reminder BOOLEAN NOT NULL DEFAULT FALSE,
    sent_at DATETIME NOT NULL,
    INDEX idx_notice_deliveries_notice (notice_id),
    INDEX idx_notice_deliveries_notice_sent (notice_id, sent_at),
    CONSTRAINT fk_notice_deliveries_notice FOREIGN KEY (notice_id) REFERENCES myco_notices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_notifications (
    id CHAR(36) PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    type ENUM('notice_delivery', 'delivery_failure', 'system') NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    notice_id CHAR(36) NULL,
    read_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_user_notifications_user (user_id, read_at),
    INDEX idx_user_notifications_created (created_at),
    INDEX idx_user_notifications_user_created (user_id, created_at),
    CONSTRAINT fk_user_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_notifications_notice FOREIGN KEY (notice_id) REFERENCES myco_notices(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
